version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile  #
    container_name: payment
    ports:
     - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    working_dir: /app/payment
    restart: always
    volumes:
#    - static_volume:/app/payment/static
    -  ./static:/app/payment/static
#    networks:
#      - mynetwork



  db:
    image: postgres:16
    container_name: db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
#    networks:
#      - mynetwork

volumes:
  postgres_data:
#  static_volume:
#networks:
#  mynetwork:
#    driver: bridge